apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: copy-protection
spec:
  selector:
    nodeSelectorLabels:
        key: value

  file:
    matchPatterns:
    - pattern: (/bzip2* | /tar* | /zip*)
  action:
    Audit
  severity: 5

